### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by fehnomenal**
- [x] Render to a file at build time to prevent giant `<style />`
  - This is done in `renderChunk` instead of `transform` as only in the render/output phase the file name of the emitted file is known.
  - [x] Handle sveltekit base path (or asset path? need to check the difference)
~~- [ ] Generate handle for the user~~ too error prone

### CODE REVIEW

**Comment by fehnomenal** [comment]
Thinking about this, I'm not really sure if we should take over generating the handle hook for the user. If they don't even have a `hooks.server.` file we would need to fake it and that gets ugly really fast (we do this with `houdini`).
Verifying the user implemented the replacement should not be that hard and probably does not need to be 100% bullet proof. Maybe it is enough to check that both strings `%unocss.global%` and `'__UnoCSS_Svelte_Scoped_global_styles__'` are present.

What do you think @jacob-8 ?

Then there is only the problem of getting kit's base path. Unfortunately, they do not expose the config or the function to load the config, so we're probably left with reading the file and `JSON.parse`ing it. Will do this later if you don't have a better idea :wink:

**Comment by fehnomenal** [comment]
Instead of checking for the correct user side implementation now an error is logged if one of the placeholder is returned inside the html during dev.

The `handle` call could be made in so many permutations that it must be easier to just check the outcome and direct the user to the docs in case of an unexpected output.

**Comment by jacob-8** [comment]
Great to see more ideas flowing, thank you! I'll look things over when I can.

**Comment by jacob-8** [comment]
Tell me more about your warning to users: "beware of the single quotes" - are you trying to instruct them to make sure to use single and not double quotes here? I don't think we want to enforce that because linters and auto formatters will change it to their preference, perhaps without them noticing. I see that in our code you escape single quotes, but is there a way we can let users use whatever format they prefer? Do we just need to escape both single and double quotes?

**Comment by jacob-8** [comment]
Did some refactoring, then found that importing the svelte.config.js breaks if vitePreprocess happens to be imported into the config, so I've removed the dependence on that. The base can be retrieved from Vite's config (yes, I checked the Vite config uses the base set in svelte.config.js and not in vite.config.js if someone happens to set in both places). I don't like the idea of trying parse the raw svelte.config.js string to discern if they've changed their hooks name so am just checking for `hooks.server` in any folder. 

You're invited to contribute to my PR itself moving forward: https://github.com/jacob-8/unocss/invitations

**Comment by fehnomenal** [comment]
Thanks for the invitation. Let's continue discussing in the main PR.

**Pull request merged**
